const FIELD_LABELS = {
  title: "عنوان",
  titleColor: "رنگ عنوان",
  "title:color": "رنگ عنوان",
  subtitle: "زیرعنوان",
  subtitleColor: "رنگ زیرعنوان",
  description: "توضیحات",
  descriptionColor: "رنگ توضیحات",
  text: "متن",
  textColor: "رنگ متن",
  image: "تصویر",
  images: "تصاویر",
  image1: "تصویر ۱",
  image2: "تصویر ۲",
  image3: "تصویر ۳",
  mainImage: "تصویر اصلی",
  beforeImage: "تصویر قبل",
  afterImage: "تصویر بعد",
  backImage: "تصویر پس‌زمینه",
  backgroundImage: "تصویر پس‌زمینه",
  dotImage: "تصویر نقطه‌چین",
  Image: "تصویر",
  logo: "لوگو",
  logoName: "آیکون لوگو",
  src: "آدرس تصویر",
  alt: "متن جایگزین تصویر",
  icon: "آیکون",
  iconName: "نام آیکون",
  quoteIcon: "آیکون ویرگول نقل‌قول",
  quoteIconColor: "رنگ آیکون ویرگول",
  iconColor: "رنگ آیکون",
  iconBg: "رنگ پس‌زمینه آیکون",
  iconBgColor: "رنگ پس‌زمینه آیکون",
  iconBoxBg: "رنگ پس‌زمینه جعبه آیکون",
  iconUp: "آیکون باز کردن",
  iconDown: "آیکون بستن",
  iconColorUp: "رنگ آیکون باز",
  iconColorDown: "رنگ آیکون بسته",
  iconColorBg: "رنگ پس‌زمینه آیکون",
  iconBorderColor: "رنگ حاشیه آیکون",
  fallbackIconColor: "رنگ آیکون جایگزین",
  fallbackText: "متن جایگزین",
  fallbackTextColor: "رنگ متن جایگزین",
  bgColor: "رنگ پس‌زمینه",
  bgShapeColor: "رنگ شکل پس‌زمینه",
  background: "رنگ پس‌زمینه",
  cardBgColor: "رنگ پس‌زمینه کارت",
  cardBackground: "رنگ پس‌زمینه کارت",
  cardTitleColor: "رنگ عنوان کارت",
  cardTextColor: "رنگ متن کارت",
  cardDescriptionColor: "رنگ توضیحات کارت",
  cardShadowColor: "رنگ سایه کارت",
  shadow: "سایه کارت‌ها",
  backColor: "رنگ پس‌زمینه",
  firstCardColor: "رنگ کارت اول",
  secondCardColor: "رنگ کارت دوم",
  shadowColor: "رنگ سایه",
  borderColor: "رنگ حاشیه",
  cardBorderColor: "رنگ حاشیه کارت",
  highlightColor: "رنگ هایلایت",
  beforeColor: "رنگ پس‌زمینه",
  nameColor: "رنگ نام",
  roleColor: "رنگ سمت شغلی",
  jobColor: "رنگ شغل",
  numberGradient: "گرادیان رنگ عدد",
  button: "دکمه",
  text_button: "متن دکمه",
  link: "لینک",
  href: "لینک",
  button_link: "لینک دکمه",
  label: "برچسب",
  id: "شناسه",
  number: "شماره",
  cards: "کارت‌ها",
  items: "آیتم‌ها",
  services: "خدمات",
  projects: "پروژه‌ها",
  Questions: "سوالات",
  cart: "افراد",
  people: "افراد",
  name: "نام",
  role: "سمت",
  job: "شغل",
  img: "تصویر",
  colors: "رنگ‌ها",
  arrows: "فلش‌ها",
  lines: "خطوط",
  color: "رنگ",
  opacity: "شفافیت",
  desktop: "دسکتاپ",
  mobile: "موبایل",
  canvasWidth: "عرض بوم",
  canvasHeight: "ارتفاع بوم",
  width: "عرض",
  height: "ارتفاع",
  top: "فاصله از بالا",
  left: "فاصله از چپ",
  before: "تصویر قبل",
  after: "تصویر بعد",
  paragraph: "متن پاراگراف",
  activeBg: "رنگ پس‌زمینه فعال",
  inactiveBg: "رنگ پس‌زمینه غیرفعال",
  activeIcon: "رنگ آیکون فعال",
  inactiveIcon: "رنگ آیکون غیرفعال",
  activeBorder: "رنگ حاشیه فعال",
  inactiveBorder: "رنگ حاشیه غیرفعال",
  activeDot: "رنگ نقطه فعال",
  dot: "رنگ نقطه",
  dotColor: "رنگ نقطه",
  activeDotColor: "رنگ نقطه فعال",
  navBgColor: "رنگ پس‌زمینه دکمه‌های ناوبری",
  paragraphColor: "رنگ متن پاراگراف",
  prevIconId: "آیکون قبلی",
  nextIconId: "آیکون بعدی",
  ArrowRight: "آیکون فلش راست",
  ArrowLeft: "آیکون فلش چپ",
  badge: "آیکون",
  imagesBg: "رنگ بک‌گراند تصاویر",
  testimonial: "نظر مشتری",
  testimonialColorSets: "رنگ‌بندی متناوب نظرات",
  enabled: "نمایش این بخش",
  authorName: "نام نویسنده نظر",
  authorColor: "رنگ نام نویسنده",
  roleText: "متن سمت شغلی",
  firstIconColor: "رنگ آیکون اول",
  firstIconName: "نام آیکون اول",
  secondIconColor: "رنگ آیکون دوم",
  secondIconName: "نام آیکون دوم",
  phonNumber: "شماره تلفن",
  phonNumberColor: "رنگ شماره تلفن",
  email: "ایمیل",
  emailColor: "رنگ ایمیل",
  iconPhone: "آیکون تلفن",
  iconPhoneColor: "رنگ آیکون تلفن",
  iconPhonebg: "رنگ پس‌زمینه آیکون تلفن",
  iconEmail: "آیکون ایمیل",
  iconEmailColor: "رنگ آیکون ایمیل",
  iconEmailbg: "رنگ پس‌زمینه آیکون ایمیل",
  addres: "آدرس",
  addresColor: "رنگ آدرس",
  iconAddres: "آیکون آدرس",
  iconAddresColor: "رنگ آیکون آدرس",
  iconAddresbg: "رنگ پس‌زمینه آیکون آدرس",
};

export function getFieldLabel(key) {
  return FIELD_LABELS[key] || key;
}
